// ══════════════════════════════════════════════════════════════════════
// INGREDIENT UNITS — Default-Einheiten für Zutaten
// Keys: lowercase Artikelname, Values: Unit-String
// Regeln:
//   Flüssigkeiten → ml
//   Schüttgut/Pulver → g  (Gewürze → TL)
//   Streichfähiges/Festes in Mengen → g
//   Löffelware → EL
//   Zählbares → "" (Stück)
//   Backzutaten in kleinen Mengen → TL oder Päckchen
//   Default → "" (Stück)
// ══════════════════════════════════════════════════════════════════════

export const INGREDIENT_UNITS: Record<string, string> = {
  // ── Obst & Gemüse (zählbar → "") ──────────────────────────────────
  "äpfel": "",
  "birnen": "",
  "bananen": "",
  "orangen": "",
  "zitronen": "",
  "limetten": "",
  "clementinen": "",
  "mandarinen": "",
  "grapefruit": "",
  "pomelo": "",
  "erdbeeren": "g",
  "heidelbeeren": "g",
  "himbeeren": "g",
  "brombeeren": "g",
  "johannisbeeren": "g",
  "stachelbeeren": "g",
  "kirschen": "g",
  "trauben": "g",
  "pflaumen": "",
  "aprikosen": "",
  "pfirsiche": "",
  "nektarinen": "",
  "mango": "",
  "ananas": "",
  "avocado": "",
  "kiwi": "",
  "melone": "",
  "wassermelone": "",
  "papaya": "",
  "maracuja": "",
  "granatapfel": "",
  "feigen": "",
  "datteln": "g",
  "tomaten": "",
  "rispentomaten": "g",
  "cherrytomaten": "g",
  "gurke": "",
  "paprika (rot)": "",
  "paprika (gelb)": "",
  "paprika (grün)": "",
  "paprika": "",
  "chili": "",
  "zucchini": "",
  "aubergine": "",
  "brokkoli": "",
  "blumenkohl": "",
  "weißkohl": "",
  "rotkohl": "",
  "grünkohl": "g",
  "rosenkohl": "g",
  "wirsing": "",
  "pak choi": "",
  "spinat": "g",
  "babyspinat": "g",
  "mangold": "",
  "rucola": "g",
  "eisbergsalat": "",
  "feldsalat": "g",
  "romanasalat": "",
  "endiviensalat": "",
  "chicorée": "",
  "lauch": "",
  "sellerie": "",
  "fenchel": "",
  "spargel": "g",
  "artischocke": "",
  "karotten": "",
  "karotte": "",
  "kartoffeln": "g",
  "süßkartoffeln": "g",
  "rote beete": "",
  "pastinaken": "",
  "steckrüben": "",
  "topinambur": "",
  "zwiebeln": "",
  "zwiebel": "",
  "rote zwiebeln": "",
  "frühlingszwiebeln": "",
  "knoblauch": "",
  "knoblauchzehe": "",
  "knoblauchzehen": "",
  "ingwer": "g",
  "pilze": "g",
  "champignons": "g",
  "pfifferlinge": "g",
  "radieschen": "",
  "rettich": "",
  "kohlrabi": "",
  "mais (frisch)": "",
  "petersilie": "",
  "basilikum (frisch)": "",
  "basilikum": "",
  "koriander": "",
  "minze": "",
  "schnittlauch": "",
  "thymian (frisch)": "",
  "rosmarin (frisch)": "",

  // ── Backwaren (zählbar → "") ──────────────────────────────────────
  "toastbrot": "",
  "vollkornbrot": "",
  "roggenbrot": "",
  "sauerteigbrot": "",
  "mehrkornbrot": "",
  "dinkelbrötchen": "",
  "baguette": "",
  "ciabatta": "",
  "focaccia": "",
  "brötchen": "",
  "schrippen": "",
  "mohnbrötchen": "",
  "laugenbrötchen": "",
  "brezel": "",
  "croissants": "",
  "hefezopf": "",
  "tortillas": "",
  "pitabrot": "",
  "naan-brot": "",
  "fladenbrot": "",
  "hamburger brötchen": "",
  "hot-dog-brötchen": "",
  "blätterteig": "",
  "hefeteig (fertig)": "",
  "kuchenteig (fertig)": "",
  "donuts": "",
  "muffins": "",

  // ── Fleisch & Wurst (g) ───────────────────────────────────────────
  "hähnchenbrust": "g",
  "hähnchenschenkel": "",
  "putenbrust": "g",
  "hackfleisch (gemischt)": "g",
  "hackfleisch (rind)": "g",
  "hackfleisch": "g",
  "rindersteak": "",
  "rinderbraten": "g",
  "gulasch (rind)": "g",
  "gulasch": "g",
  "schweinefilet": "g",
  "schweineschnitzel": "",
  "schweinebauch": "g",
  "lammkeule": "g",
  "kalbsschnitzel": "",
  "bratwurst": "",
  "speck": "g",
  "salami": "g",
  "chorizo": "g",
  "schinken": "g",
  "kochschinken": "g",
  "pastrami": "g",
  "mortadella": "g",
  "fleischwurst": "g",
  "leberwurst": "g",
  "lachs": "g",
  "räucherlachs": "g",
  "kabeljau": "g",
  "forelle": "",
  "dorade": "",
  "tilapia": "g",
  "makrele": "",
  "thunfisch (dose)": "",
  "garnelen": "g",
  "miesmuscheln": "g",
  "jakobsmuscheln": "",
  "rollmops": "",
  "matjes": "",

  // ── Milch & Käse ──────────────────────────────────────────────────
  "vollmilch": "ml",
  "fettarme milch": "ml",
  "laktosefreie milch": "ml",
  "milch": "ml",
  "hafermilch": "ml",
  "mandelmilch": "ml",
  "sojamilch": "ml",
  "alpro hafer-drink": "ml",
  "alpro mandel-drink": "ml",
  "alpro soja-drink": "ml",
  "oatly haferdrink": "ml",
  "oatly barista": "ml",
  "butter": "g",
  "margarine": "g",
  "joghurt (natur)": "g",
  "joghurt (frucht)": "g",
  "joghurt": "g",
  "griechischer joghurt": "g",
  "müller joghurt": "g",
  "danone joghurt": "g",
  "activia": "",
  "actimel": "",
  "schmand": "g",
  "crème fraîche": "g",
  "sahne": "ml",
  "schlagsahne": "ml",
  "saure sahne": "g",
  "kondensmilch": "ml",
  "buttermilch": "ml",
  "kefir": "ml",
  "skyr": "g",
  "quark": "g",
  "frischkäse": "g",
  "philadelphia": "g",
  "boursin": "g",
  "bresso": "g",
  "mascarpone": "g",
  "ricotta": "g",
  "hüttenkäse": "g",
  "schmelzkäse": "g",
  "mozzarella": "g",
  "gouda": "g",
  "parmesan": "g",
  "emmentaler": "g",
  "feta": "g",
  "brie": "g",
  "camembert": "",
  "gruyère": "g",
  "manchego": "g",
  "pecorino": "g",
  "edamer": "g",
  "käse": "g",

  // ── Eier (zählbar) ────────────────────────────────────────────────
  "eier (6er)": "",
  "eier (10er)": "",
  "eier (12er)": "",
  "bio-eier (6er)": "",
  "freilandeier (10er)": "",
  "wachteleier": "",
  "ei": "",
  "eier": "",

  // ── Nudeln & Reis (g) ─────────────────────────────────────────────
  "spaghetti": "g",
  "fusilli": "g",
  "penne": "g",
  "rigatoni": "g",
  "tagliatelle": "g",
  "farfalle": "g",
  "linguine": "g",
  "lasagneplatten": "",
  "eiernudeln": "g",
  "spätzle": "g",
  "gnocchi": "g",
  "reisnudeln": "g",
  "glasnudeln": "g",
  "nudeln": "g",
  "basmati reis": "g",
  "jasmin reis": "g",
  "risotto reis": "g",
  "vollkorn reis": "g",
  "reis": "g",
  "couscous": "g",
  "bulgur": "g",
  "quinoa": "g",
  "polenta": "g",
  "linsen (rote)": "g",
  "linsen (grüne)": "g",
  "linsen": "g",
  "kichererbsen (trocken)": "g",

  // ── Konserven (zählbar / Dosen) ───────────────────────────────────
  "passierte tomaten": "ml",
  "tomatenmark": "EL",
  "dosentomaten (gehackt)": "",
  "dosentomaten": "",
  "kidneybohnen": "",
  "weiße bohnen": "",
  "schwarze bohnen": "",
  "cannellini-bohnen": "",
  "kichererbsen": "",
  "linsen (dose)": "",
  "mais": "",
  "erbsen": "",
  "champignons (dose)": "",
  "kokosmilch": "ml",
  "sardinen": "",
  "thunfisch (dose, natur)": "",
  "krabben (dose)": "",
  "lachsfilet (dose)": "",
  "anchovis": "",
  "oliven": "g",
  "artischocken": "",
  "kapern": "EL",
  "rote beete (dose)": "",
  "sauerkraut (dose)": "",
  "ananasscheiben": "",
  "pfirsiche (dose)": "",
  "mandarin-orangen (dose)": "",
  "gurkenscheiben (eingelegte)": "",

  // ── Saucen & Gewürze ──────────────────────────────────────────────
  "salz": "TL",
  "meersalz": "TL",
  "pfeffer": "TL",
  "olivenöl": "EL",
  "sonnenblumenöl": "EL",
  "rapsöl": "EL",
  "sesamöl": "EL",
  "kokosöl": "EL",
  "leinöl": "EL",
  "kürbiskernöl": "EL",
  "trüffelöl": "EL",
  "öl": "EL",
  "essig": "EL",
  "balsamico": "EL",
  "weißweinessig": "EL",
  "apfelessig": "EL",
  "sojasauce": "EL",
  "sojasoße": "EL",
  "sojasoße (dunkel)": "EL",
  "fischsauce": "EL",
  "austernsoße": "EL",
  "teriyakisoße": "EL",
  "worcestersauce": "EL",
  "tabasco": "TL",
  "sriracha": "EL",
  "wasabi": "TL",
  "ketchup": "EL",
  "senf": "EL",
  "mayonnaise": "EL",
  "bbq-sauce": "EL",
  "hollandaise": "ml",
  "sahnesoße": "ml",
  "bratensauce": "ml",
  "béchamelsoße": "ml",
  "tomatensoße (fertig)": "ml",
  "pesto": "EL",
  "gemüsebrühe": "ml",
  "hühnerbrühe": "ml",
  "rinderbrühe": "ml",
  "brühe": "ml",
  "oregano": "TL",
  "basilikum (getr.)": "TL",
  "thymian (getr.)": "TL",
  "rosmarin (getr.)": "TL",
  "salbei": "TL",
  "estragon": "TL",
  "dill": "TL",
  "majoran": "TL",
  "petersilie (getr.)": "TL",
  "fenchelsamen": "TL",
  "paprikapulver": "TL",
  "chilipulver": "TL",
  "chiliflocken": "TL",
  "kreuzkümmel": "TL",
  "korianderpulver": "TL",
  "currypulver": "TL",
  "kurkuma": "TL",
  "ingwerpulver": "TL",
  "knoblauchpulver": "TL",
  "zwiebelpulver": "TL",
  "zimt": "TL",
  "muskat": "TL",
  "muskatnuss": "TL",
  "nelken": "TL",
  "kardamom": "TL",
  "sternanis": "",
  "lorbeerblatt": "",
  "lorbeerblätter": "",
  "szechuanpfeffer": "TL",
  "vanille": "TL",
  "vanillezucker": "",
  "vanilleextrakt": "TL",
  "backpulver": "TL",
  "natron": "TL",
  "mehl": "g",
  "vollkornmehl": "g",
  "dinkelmehl": "g",
  "weizenmehl": "g",
  "zucker": "g",
  "brauner zucker": "g",
  "puderzucker": "g",
  "paniermehl": "g",
  "speisestärke": "EL",
  "hefe (trocken)": "",
  "hefe": "",
  "trockenhefe": "",

  // ── Kaffee & Tee ──────────────────────────────────────────────────
  "kaffee (gemahlen)": "g",
  "kaffee (bohnen)": "g",
  "espresso": "",
  "kaffeepads": "",
  "kaffeekapseln": "",
  "schwarztee": "",
  "grüntee": "",
  "kräutertee": "",
  "kamillentee": "",
  "pfefferminztee": "",
  "ingwertee": "",
  "matcha": "TL",

  // ── Müsli & Frühstück ─────────────────────────────────────────────
  "haferflocken": "g",
  "dinkelflocken": "g",
  "müsli": "g",
  "granola": "g",
  "porridge": "g",
  "cornflakes": "g",
  "chiasamen": "EL",
  "leinsamen": "EL",
  "marmelade": "EL",
  "erdbeerkonfitüre": "EL",
  "nutella": "EL",
  "erdnussbutter": "EL",
  "mandelmus": "EL",
  "honig": "EL",
  "ahornsirup": "EL",
  "agavendicksaft": "EL",
  "pfannkuchenmix": "g",

  // ── Tiefkühl ──────────────────────────────────────────────────────
  "tiefkühl-erbsen": "g",
  "tiefkühl-spinat": "g",
  "tiefkühl-brokkoli": "g",
  "tiefkühl-blumenkohl": "g",
  "tiefkühl-gemüsemix": "g",
  "tiefkühl-erbsen & karotten": "g",
  "tiefkühl-edamame": "g",
  "tiefkühl-rote beete": "g",
  "tiefkühl-maiskölbchen": "g",
  "tiefkühl-früchtemix": "g",
  "tiefkühl-beeren": "g",
  "tiefkühl-mango": "g",
  "tiefkühl-pommes": "g",
  "tiefkühl-kroketten": "g",
  "fischstäbchen": "",
  "tiefkühl-lachs": "g",
  "tiefkühl-garnelen": "g",
  "tiefkühl-hähnchen": "g",
  "tiefkühl-schnitzel": "",
  "tiefkühl-pizza": "",

  // ── Getränke ──────────────────────────────────────────────────────
  "wasser": "ml",
  "mineralwasser": "ml",
  "saft": "ml",
  "orangensaft": "ml",
  "apfelsaft": "ml",
  "wein": "ml",
  "rotwein": "ml",
  "weißwein": "ml",
  "bier": "ml",
  "prosecco": "ml",
  "rum": "ml",
  "wodka": "ml",
  "whisky": "ml",
  "likör": "ml",

  // ── Veggie & Bio ──────────────────────────────────────────────────
  "tofu": "g",
  "tempeh": "g",
  "seitan": "g",
  "räuchertofu": "g",
  "sojaschnetzel": "g",
  "vegane sahne": "ml",
  "veganer käse": "g",

  // ── Nüsse & Samen ─────────────────────────────────────────────────
  "mandeln": "g",
  "walnüsse": "g",
  "haselnüsse": "g",
  "cashews": "g",
  "pistazien": "g",
  "pinienkerne": "g",
  "sonnenblumenkerne": "g",
  "kürbiskerne": "g",
  "sesam": "EL",
  "kokosraspel": "g",
  "kokosflocken": "g",
  "nüsse": "g",

  // ── Sonstiges Kochen ──────────────────────────────────────────────
  "gelatine": "",
  "agar-agar": "TL",
  "tortenguss": "",
  "schokoglasur": "g",
  "kakaopulver": "EL",
  "kakao": "EL",
  "schokolade": "g",
  "zartbitterschokolade": "g",
  "vollmilchschokolade": "g",
  "weiße schokolade": "g",
  "schokodrops": "g",
  "rosinen": "g",
  "cranberries": "g",
  "kokoszucker": "g",
  "erythrit": "g",
  "xucker": "g",
  "marzipan": "g",
  "fondant": "g",
};
